version: '3.8'

services:
  backend:
    build: .
    container_name: headway-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=headway_learning
      - JWT_SECRET=your_secret_key
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:14
    container_name: headway-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: headway_learning
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
